### ISSUE TITLE
[Feature] Arrow damage according to force

### ISSUE THREAD

**Issue by Lix3nn53** [Eniripsa96/SkillAPIKotlin#3]
When I have projectile-damage attribute and shoot bow, it adds same damage at pull force 0.1 and 0.9 etc.

Its possible to reduce damage bonus according to EntityShootBowEvent.getForce()

**Comment by Eniripsa96** [comment]
Could you use a multiplier instead of flat damage? The plugin doesn't know the difference between additive and multiplicative formulas so separating out your bonus and applying extra operations on it would be tricky.

**Comment by Lix3nn53** [comment]
I didnt understand what you are suggesting but sorry if I wasn't clear enough, I just want projectile-damage bonus to change like this when the projectile is an arrow: 
newBonus = oldBonus x EntityShootBowEvent#getForce()

You dont want to make this default?

**Comment by Eniripsa96** [comment]
Are you referring to buffs or attributes? 

Attributes use formulas to adjust the damage so there is no concept of "bonus", only some final modified value. The plugin doesn't know if you're doing a flat bonus like "a+v", a multiplier like "v(a*0.1+1)". or something in between so "bonus" would be derived and situational (if you already are using a multiplier, there's no point in also adjusting based on the force since base arrow damage is already dependent on that). I can't choose one or the other either since there's the in between cases that are possible like "v(a*0.01+1)+a*0.01".

As for buffs, those are a generic modifier used for all sorts of numbers so adding in extra logic for specifically projectiles would complicate things quite a bit.

**Comment by Lix3nn53** [comment]
Problem: if target is close an archer can spam arrows by "instant charge & release" to deal full damage which is broken
Cause: flat damage increases like "a+v" doesn't get effected by force
Solution: multiply final final damage with force

I think this should be default like vanilla. I understand If its complicated or extra special tho. Just a suggestion

**Comment by Eniripsa96** [comment]
The one issue with just multiplying the final result by the force is then it is applied to base damage twice. For example:

Strategy | Full Charge | Medium Charge | No Charge | How
-- | -- | -- | -- | --
Vanilla | 9 | 6 | 1 | base
2 Bonus Damage | 11 | 8 | 3 | base + 2
Modified 2 Bonus Damage | 11 | 5.33 | 0.33 | force * (base + 2)
Double Damage | 18 | 12 | 2 | base * 2
Modified Double Damage | 18 | 8 | 0.2 | force * (base * 2)

So it ends up penalizing anything but fully powered arrows more than normal even with bonus cases, and multipliers just become a huge problem, doing one-tenth the damage which it should do.

Now, applying force to the difference from base to modified value can work for bonus values, as seen below, but still doesn't work for multipliers or mixed equations:

Strategy | Full Charge | Medium Charge | No Charge | How
-- | -- | -- | -- | --
Vanilla | 9 | 6 | 1 | base
2 Bonus Damage | 11 | 8 | 3 | base + 2
Modified 2 Bonus Damage | 11 | 7.33 | 1.22 | base + force * (base + 2 - base)
Double Damage | 18 | 12 | 2 | base * 2
Modified Double Damage | 18 | 10 | 1.11 | base + force * (base * 2 - base)

It can't be enabled by default due to this. Adding an option to enable it and adding in the complexities around handling arrows could be done if needed, but I would recommend considering using multipliers as they work without any changes with force and can be more consistent in terms of how valuable the bonus is. For example, given vanilla bow damage and a formula of "a+v", you can instead use "v(a*0.11+1)" which would both be the same for fully powered bows and work with force. Is there something stopping you from doing that?

**Comment by Lix3nn53** [comment]
Thanks for the detailed explanation. I am using this attribute as base damage of ranged weapons thanks to lore attribute feature, thats why I asked for this. I didnt know about formula "v(a*0.11+1)" and it works great. Thanks!
